### ISSUE TITLE
[Bug] "_" in template is replaced with "-"

### ISSUE THREAD

**Issue by wertzui** [BlueBasher/easy-branch-creator#5] opened 2023-01-05 14:32 UTC
My template is the following
```
feature/${System.Id}_${System.Title}
```

However the final branch name comes out like this
```
feature/123-Some_Title
```

So the `_` from the template is replaced with a `-` in the final branch name.

**Comment by BlueBasher** [comment] 2023-01-19 12:11
The issue is fixed in PR #7 and has been released as version 0.1.45.

**Closed by BlueBasher** 2023-01-19 12:11 UTC
